{
  "openapi": "3.0.3",
  "info": {
    "title": "Deveel Omni-Channel Messaging API",
    "version": "v1",
    "description": {
      "$ref": "description.md"
    },
    "contact": {
      "name": "Antonello Provenzano",
      "email": "antonello@deveel.com"
    },
    "license": {
      "name": "Deveel EULA",
      "url": "https://docs.ocm.deveel.net/LICENSE.html"
    },
    "x-logo": {
      "url": "https://github.com/deveel/deveel.ocm.openapi-docs/raw/main/deveel-logo.png"
    }
  },
  "servers": [
    {
      "url": "https://api.ocm.deveel.net"
    }
  ],
  "paths": {
    "/message/batch": {
      "post": {
        "tags": [
          "message"
        ],
        "summary": "Sends a batch of Messages",
        "operationId": "message_batchSend",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      }
    },
    "/message/": {
      "post": {
        "tags": [
          "message"
        ],
        "summary": "Sends a single Message",
        "operationId": "message_send",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      }
    },
    "/message/state/subscription": {
      "get": {
        "tags": [
          "message"
        ],
        "summary": "Gets a page of Message State Subscriptions",
        "operationId": "message_getSubscriptions",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      }
    },
    "/message/{id}/state": {
      "get": {
        "tags": [
          "message"
        ],
        "summary": "Gets the State of a Message",
        "operationId": "message_getState",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      }
    },
    "/message/received/{id}": {
      "get": {
        "tags": [
          "message"
        ],
        "summary": "Gets a Received Message from Cache",
        "operationId": "message_getReceived",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    },
    "/message/receiver/": {
      "post": {
        "tags": [
          "receiver"
        ],
        "summary": "Creates a new Receiver of Incoming Messages",
        "operationId": "receiver_create",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    },
    "/message/receiver/{id}": {
      "get": {
        "tags": [
          "receiver"
        ],
        "summary": "Gets a Receiver of Incoming Messages",
        "operationId": "receiver_get",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "receiver"
        ],
        "summary": "Deletes a given Message Receiver",
        "operationId": "receiver_delete",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "receiver"
        ],
        "summary": "Updates the information of a Message Receiver",
        "operationId": "receiver_update",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    },
    "/message/receiver/page": {
      "get": {
        "tags": [
          "receiver"
        ],
        "summary": "Gets a page of Message Receivers",
        "operationId": "receiver_getPage",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "send:message": "Send messages or batch of messages to individuals",
              "receive:message": "Receive messages from individuals",
              "read:channel": "Read-only access to user Channels",
              "create:channel": "Create new user Channels",
              "update:channel": "Update settings of existing user Channels",
              "delete:channel": "Delete existing user Channels",
              "read:phone": "Read-only access to server phone numbers",
              "create:phone": "Request the registration of server phone numbers",
              "update:phone": "Update the status and settings of server phone numbers",
              "delete:phone": "Delete a server phone numbers",
              "read:email": "Read-only access to server email addresses",
              "create:email": "Request the registration of server email addresses",
              "update:email": "Update the status and settings of server email addresses",
              "delete:email": "Delete a server phone number",
              "read:label": "Read-only access to server alpha-numeric labels",
              "create:label": "Request the registration of server alpha-numeric labels",
              "update:label": "Update the status and settings of server alpha-numeric labels",
              "delete:label": "Delete a server alpha-numeric labels"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://deveel.eu.auth0.com/authorize",
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "send:message": "Send messages or batch of messages to individuals",
              "receive:message": "Receive messages from individuals",
              "read:channel": "Read-only access to user Channels",
              "create:channel": "Create new user Channels",
              "update:channel": "Update settings of existing user Channels",
              "delete:channel": "Delete existing user Channels",
              "read:phone": "Read-only access to server phone numbers",
              "create:phone": "Request the registration of server phone numbers",
              "update:phone": "Update the status and settings of server phone numbers",
              "delete:phone": "Delete a server phone numbers",
              "read:email": "Read-only access to server email addresses",
              "create:email": "Request the registration of server email addresses",
              "update:email": "Update the status and settings of server email addresses",
              "delete:email": "Delete a server phone number",
              "read:label": "Read-only access to server alpha-numeric labels",
              "create:label": "Request the registration of server alpha-numeric labels",
              "update:label": "Update the status and settings of server alpha-numeric labels",
              "delete:label": "Delete a server alpha-numeric labels"
            }
          }
        }
      }
    }
  }
}