openapi: 3.0.3
info:
  title: Deveel OCM API
  version: v1
  description: Deveel Omni-Channel Messaging API
  contact:
    name: Antonello Provenzano
    email: antonello@deveel.com
  license:
    name: Deveel EULA
    url: 'https://docs.ocm.deveel.net/LICENSE.html'
  x-logo:
    url: 'https://github.com/deveel/deveel.ocm.openapi-docs/raw/main/deveel-logo.png'
servers:
  - url: 'https://api.ocm.deveel.net'
paths:
  /message/batch:
    $ref: paths\message@batch.yaml
  /message:
    $ref: paths\message.yaml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://deveel.eu.auth0.com/oauth/token'
          scopes:
            'message:send': Send messages to individuals
            'message:receive': Receive messages from individuals
