{
  "openapi": "3.0.3",
  "info": {
    "title": "Deveel OCM API",
    "version": "v1",
    "description": "Specifications of the Deveel Omni-Channel Messaging API v1",
    "contact": {
      "name": "Antonello Provenzano",
      "email": "antonello@deveel.com"
    },
    "license": {
      "name": "Deveel EULA",
      "url": "https://docs.ocm.deveel.net/LICENSE.html"
    },
    "x-logo": {
      "url": "https://github.com/deveel/deveel.ocm.openapi-docs/raw/main/deveel-logo.png"
    }
  },
  "servers": [
    {
      "url": "https://api.ocm.deveel.net"
    }
  ],
  "paths": {
    "/channel/": {
      "post": {
        "tags": [
          "channel"
        ],
        "summary": "Requests a new Channel",
        "operationId": "channel_request",
        "security": [
          {
            "oauth2": [
              "create:channel"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets all Channels",
        "operationId": "channel_getAll",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/{channelId}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel",
        "operationId": "channel_get",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/{channelId}/credentials": {
      "put": {
        "tags": [
          "channel"
        ],
        "summary": "Updates the Channel Credentials",
        "operationId": "channel_updateCredentials"
      }
    },
    "/terminal/email/{id}": {
      "get": {
        "tags": [
          "email"
        ],
        "summary": "Gets an E-Mail",
        "operationId": "emailAddress_get",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/email": {
      "get": {
        "tags": [
          "email"
        ],
        "summary": "Gets a page of E-Mails",
        "operationId": "emailAddress_getPage",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/phone/{id}": {
      "get": {
        "tags": [
          "phone"
        ],
        "summary": "Gets a Phone Number",
        "operationId": "phoneNumber_get",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/phone": {
      "get": {
        "tags": [
          "phone"
        ],
        "summary": "Gets a page of Phone Numbers",
        "operationId": "phoneNumber_getPage",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/": {
      "post": {
        "tags": [
          "terminal"
        ],
        "summary": "Requests a Terminal",
        "operationId": "terminal_request",
        "security": [
          {
            "oauth2": [
              "request:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/{id}": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a Terminal",
        "operationId": "terminal_get",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/message/receiver/": {
      "post": {
        "tags": [
          "receiver"
        ],
        "summary": "Creates a new Receiver of Incoming Messages",
        "operationId": "receiver_create",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    },
    "/message/receiver/{id}": {
      "get": {
        "tags": [
          "receiver"
        ],
        "summary": "Gets a Receiver of Incoming Messages",
        "operationId": "receiver_get",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "receiver"
        ],
        "summary": "Deletes a given Message Receiver",
        "operationId": "receiver_delete",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "receiver"
        ],
        "summary": "Updates the information of a Message Receiver",
        "operationId": "receiver_update",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    },
    "/message/receiver/page": {
      "get": {
        "tags": [
          "receiver"
        ],
        "summary": "Gets a page of Message Receivers",
        "operationId": "receiver_getPage",
        "security": [
          {
            "oauth2": [
              "receive:message"
            ]
          }
        ]
      }
    },
    "/message/state/subscription": {
      "post": {
        "tags": [
          "message"
        ],
        "summary": "Subscribes to Messages States",
        "operationId": "messageState_subscribe"
      },
      "get": {
        "tags": [
          "message"
        ],
        "summary": "Gets a page of Message State Subscriptions",
        "operationId": "messageState_getSubscriptions",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      }
    },
    "/message/state/subscription/{id}": {
      "get": {
        "tags": [
          "message"
        ],
        "summary": "Gets a Subscription to Messages States",
        "operationId": "messageState_getSubscription",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "message"
        ],
        "summary": "Unsubscribes from Message States",
        "operationId": "messageState_unsubscribe",
        "security": [
          {
            "oauth2": [
              "send:message"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:channel": "Read-only access to user Channels",
              "create:channel": "Create new user Channels",
              "update:channel": "Update settings of existing user Channels",
              "delete:channel": "Delete existing user Channels",
              "request:terminal": "Request the assignment of existing or new terminals",
              "delete:terminal": "Delete existing terminals",
              "read:terminal": "Read access to the terminals",
              "send:message": "Configure notifications of message state changes",
              "receive:message": "Configure routing of incoming messages"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://deveel.eu.auth0.com/authorize",
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:channel": "Read-only access to user Channels",
              "create:channel": "Create new user Channels",
              "update:channel": "Update settings of existing user Channels",
              "delete:channel": "Delete existing user Channels",
              "request:terminal": "Request the assignment of existing or new terminals",
              "delete:terminal": "Delete existing terminals",
              "read:terminal": "Read access to the terminals",
              "send:message": "Configure notifications of message state changes",
              "receive:message": "Configure routing of incoming messages"
            }
          }
        }
      }
    }
  }
}