{
  "openapi": "3.0.3",
  "info": {
    "title": "Deveel OCM API",
    "version": "v1",
    "description": "Specifications of the Deveel Omni-Channel Messaging API v1",
    "contact": {
      "name": "Antonello Provenzano",
      "email": "antonello@deveel.com"
    },
    "license": {
      "name": "Deveel EULA",
      "url": "https://docs.ocm.deveel.net/LICENSE.html"
    },
    "x-logo": {
      "url": "https://github.com/deveel/deveel.ocm.openapi-docs/raw/main/deveel-logo.png"
    }
  },
  "servers": [
    {
      "url": "https://api.ocm.deveel.net"
    }
  ],
  "paths": {
    "/client": {
      "post": {
        "tags": [
          "client"
        ],
        "summary": "Creates a Client",
        "operationId": "client_create",
        "security": [
          {
            "oauth2": [
              "create:client"
            ]
          }
        ]
      }
    },
    "/client/{id}": {
      "get": {
        "tags": [
          "client"
        ],
        "summary": "Gets a Client",
        "operationId": "client_get",
        "security": [
          {
            "oauth2": [
              "read:client"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "client"
        ],
        "summary": "Deletes a Client",
        "operationId": "client_delete",
        "security": [
          {
            "oauth2": [
              "delete:client"
            ]
          }
        ]
      }
    },
    "/user": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Create a New User",
        "operationId": "user_create",
        "security": [
          {
            "oauth2": [
              "create:user"
            ]
          }
        ]
      }
    },
    "/user/{id}": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets a User",
        "operationId": "user_get",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/user/me": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets the Current User",
        "operationId": "user_getMe",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/user/page": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Gets a Page of Users",
        "operationId": "user_getPage",
        "security": [
          {
            "oauth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/user/{id}/status": {
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Sets the Status of a User",
        "operationId": "user_setStatus",
        "security": [
          {
            "oauth2": [
              "write:tenant",
              "update:user"
            ]
          }
        ]
      }
    },
    "/channel/request/{id}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel Assignment Request",
        "operationId": "channel_getRequest",
        "security": [
          {
            "oauth2": [
              "request:channel"
            ]
          }
        ]
      }
    },
    "/channel/request": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets all Channel Assignment Requests",
        "operationId": "channel_getRequests",
        "security": [
          {
            "oauth2": [
              "request:channel"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "channel"
        ],
        "summary": "Requests the Assignment of a Channel",
        "operationId": "channel_request",
        "security": [
          {
            "oauth2": [
              "request:channel"
            ]
          }
        ]
      }
    },
    "/channel/": {
      "post": {
        "tags": [
          "channel"
        ],
        "summary": "Creates a new Channel",
        "operationId": "channel_create",
        "security": [
          {
            "oauth2": [
              "create:channel"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets all Channels",
        "operationId": "channel_listAll",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/{channelId}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel",
        "operationId": "channel_get",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/name/{channelName}": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a Channel by Name",
        "operationId": "channel_getByName",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/page": {
      "get": {
        "tags": [
          "channel"
        ],
        "summary": "Gets a page of Channels",
        "operationId": "channel_getPage",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/{channelId}/credentials": {
      "put": {
        "tags": [
          "channel"
        ],
        "summary": "Updates the Channel Credentials",
        "operationId": "channel_updateCredentials",
        "security": [
          {
            "oauth2": [
              "update:channel"
            ]
          }
        ]
      }
    },
    "/channel/{channelName}": {
      "head": {
        "tags": [
          "channel"
        ],
        "summary": "Checks if a Channel Exists",
        "operationId": "channel_exists",
        "security": [
          {
            "oauth2": [
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/inventory/{channelId}": {
      "get": {
        "tags": [
          "channel",
          "inventory"
        ],
        "summary": "Gets a Channel from the Inventory",
        "operationId": "channel_getInventoryItem",
        "security": [
          {
            "oauth2": [
              "read:inventory",
              "read:channel"
            ]
          }
        ]
      }
    },
    "/channel/inventory": {
      "get": {
        "tags": [
          "channel",
          "inventory"
        ],
        "summary": "Gets a Page of Channels from the Inventory",
        "operationId": "channel_getInventoryPage",
        "security": [
          {
            "oauth2": [
              "read:inventory",
              "read:channel"
            ]
          }
        ]
      }
    },
    "/terminal/request": {
      "post": {
        "tags": [
          "terminal"
        ],
        "summary": "Requests a Terminal",
        "operationId": "terminal_request",
        "security": [
          {
            "oauth2": [
              "request:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/{id}": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a Terminal",
        "operationId": "terminal_get",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a page of Terminals",
        "operationId": "terminal_getPage",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/lookup": {
      "post": {
        "tags": [
          "terminal"
        ],
        "summary": "Looks up a Terminal",
        "operationId": "terminal_lookup",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/terminal/request/{id}": {
      "get": {
        "tags": [
          "terminal"
        ],
        "summary": "Gets a Terminal Assignment Request",
        "operationId": "terminal_getRequest",
        "security": [
          {
            "oauth2": [
              "read:terminal"
            ]
          }
        ]
      }
    },
    "/route/": {
      "post": {
        "tags": [
          "route"
        ],
        "summary": "Creates a new Route of Incoming Messages",
        "operationId": "route_create",
        "security": [
          {
            "oauth2": [
              "create:route"
            ]
          }
        ]
      }
    },
    "/route/{id}": {
      "get": {
        "tags": [
          "route"
        ],
        "summary": "Gets a Route of Incoming Messages",
        "operationId": "route_get",
        "security": [
          {
            "oauth2": [
              "read:route"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "route"
        ],
        "summary": "Deletes a given Message Route",
        "operationId": "route_delete",
        "security": [
          {
            "oauth2": [
              "delete:route"
            ]
          }
        ]
      }
    },
    "/route/{routeId}/status": {
      "put": {
        "tags": [
          "message",
          "route"
        ],
        "summary": "Updates the Status of a Message Route",
        "operationId": "route_setStatus",
        "security": [
          {
            "oauth2": [
              "update:route"
            ]
          }
        ]
      }
    },
    "/route/page": {
      "get": {
        "tags": [
          "route"
        ],
        "summary": "Gets a page of Message Routes",
        "operationId": "route_getPage",
        "security": [
          {
            "oauth2": [
              "read:route"
            ]
          }
        ]
      }
    },
    "/webhook/subscription": {
      "post": {
        "tags": [
          "webhook"
        ],
        "summary": "Subscribes to Messages States",
        "operationId": "webhook_subscribe"
      },
      "get": {
        "tags": [
          "webhook"
        ],
        "summary": "Gets a page of Webhook Subscriptions",
        "operationId": "webhook_getSubscriptions",
        "security": [
          {
            "oauth2": [
              "read:webhook_subscription"
            ]
          }
        ]
      }
    },
    "/webhook/subscription/{id}": {
      "get": {
        "tags": [
          "webhook"
        ],
        "summary": "Gets a Subscription to Webhooks",
        "operationId": "webhook_getSubscription",
        "security": [
          {
            "oauth2": [
              "read:webhook_subscription"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "webhook"
        ],
        "summary": "Unsubscribes from Webhooks",
        "operationId": "webhook_unsubscribe",
        "security": [
          {
            "oauth2": [
              "unsubscribe:webhook"
            ]
          }
        ]
      }
    },
    "/webhook/subscription/{id}/status": {
      "put": {
        "tags": [
          "webhook"
        ],
        "summary": "Sets the Subscription Status",
        "operationId": "webhook_setStatus",
        "security": [
          {
            "oauth2": [
              "update:webhook_subscription"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:channel": "Read-only access to user Channels",
              "create:channel": "Create new user Channels",
              "update:channel": "Update settings of existing user Channels",
              "delete:channel": "Delete existing user Channels",
              "request:terminal": "Request the assignment of existing or new terminals",
              "delete:terminal": "Delete existing terminals",
              "read:terminal": "Read access to the terminals",
              "create:route": "Create new inbound message routes",
              "read:route": "Read access to message routes",
              "update:route": "Update existing message routes",
              "delete:route": "Delete existing message routes",
              "send:message": "Configure notifications of message state changes"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://deveel.eu.auth0.com/authorize",
            "tokenUrl": "https://deveel.eu.auth0.com/oauth/token",
            "scopes": {
              "read:channel": "Read-only access to user Channels",
              "create:channel": "Create new user Channels",
              "update:channel": "Update settings of existing user Channels",
              "delete:channel": "Delete existing user Channels",
              "request:terminal": "Request the assignment of existing or new terminals",
              "delete:terminal": "Delete existing terminals",
              "read:terminal": "Read access to the terminals",
              "create:route": "Create new inbound message routes",
              "read:route": "Read access to message routes",
              "update:route": "Update existing message routes",
              "delete:route": "Delete existing message routes",
              "send:message": "Configure notifications of message state changes"
            }
          }
        }
      }
    }
  }
}