name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          
      - name: Install dependencies
        run: npm install redoc
          
      - name: Bundle ReDoc
        run: |
          npm run build
          npx redoc-cli bundle --output ./bundle/index.html --cdn -t ./docs/template.hbs ./openapi/openapi.yaml
      
      - name: Copy Files and folders
        run: |
           copy ./docs/favicon.png ./bundle/favicon.png
           copy ./assets/CNAME ./bundle/CNAME
           copy ./docs/pages/* ./bundle

      - name: GitHub Pages v3
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bundle
