name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          
      - name: Install dependencies
        run: |
          npm install @redocly/openapi-cli
          npm install redoc
          
      - name: Bundle ReDoc
        run: |
          npx openapi bundle ./openapi/openapi.yaml --output ./dist.yaml
          npx redoc-cli bundle --output ./redoc/index.html ./dist.yaml
          cp ./docs/favicon.png ./redoc/favicon.png
          cp ./assets/CNAME ./redoc/CNAME
          sed -i '7 i \ \ <link rel="icon" type="image/png" href="favicon.png"/>' ./redoc/index.html
        
      - name: GitHub Pages v3
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redoc
