name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          
      - name: Install dependencies
        run: |
          npm install redoc
          npm install openapi-merge-cli
          
      - name: Merge OpenAPI Specs
        run: |
          npx openapi-merge-cli
          
      - name: Bundle ReDoc
        run: |
          npx redoc-cli bundle --output ./redoc/index.html ocm-api-v1.json
          cp ./docs/favicon.png ./redoc/favicon.png
          sed -i '7 i \ \ <link rel="icon" type="image/png" href="favicon.png"/>' ./redoc/index.html
        
      - name: GitHub Pages v3
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redoc
          
#      - name: Deploy to Azure
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          # Action to perform
#          action: upload
#          # Directory location of the application source code
#          app_location: ./
#          # Required token
#          azure_static_web_apps_api_token:  ${{ secrets.AZURE_WEB_APP_TOKEN }}
#          # Skips the build step for the application source code if set to true.
#          skip_app_build: true
