name: Node.js CI

on:
  # push:
  #   branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          
      - name: Install dependencies
        run: npm install redoc
          
      - name: Bundle ReDoc
        run: |
          npm run build
          npx redoc-cli bundle --output ./docs/api/data/message/v1/index.html --cdn -t ./.redoc/template.hbs https://raw.githubusercontent.com/deveel/deveel.ocm.specs/main/specs/message/data/v1/message-v1.json
          npx redoc-cli bundle --output ./docs/api/management/channel/v1/index.html --cdn -t ./.redoc/template.hbs https://raw.githubusercontent.com/deveel/deveel.ocm.specs/main/specs/channel/management/v1/channel-v1.json
          npx redoc-cli bundle --output ./docs/api/management/terminal/v1/index.html --cdn -t ./.redoc/template.hbs https://raw.githubusercontent.com/deveel/deveel.ocm.specs/main/specs/terminal/management/v1/terminal-v1.json
          npx redoc-cli bundle --output ./docs/api/management/route/v1/index.html --cdn -t ./.redoc/template.hbs https://raw.githubusercontent.com/deveel/deveel.ocm.specs/main/specs/route/management/v1/route-v1.json
          npx redoc-cli bundle --output ./docs/api/management/webhook/v1/index.html --cdn -t ./.redoc/template.hbs https://raw.githubusercontent.com/deveel/deveel.ocm.specs/main/specs/webhook/management/v1/webhook-v1.json
      
      - name: GitHub Pages v3
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
